// ============================================================
// 交互式问答向导：步骤与问题清单（静态配置）
// ============================================================

import type { WizardQuestion, WizardStep } from './resume'

/** 向导步骤定义 */
export const RESUME_WIZARD_STEPS: WizardStep[] = [
  {
    id: 'step_basic',
    title: '基本信息',
    description: '让招聘方快速了解你是谁、如何联系你',
    order: 1,
    questionIds: ['q_name', 'q_headline', 'q_email', 'q_phone', 'q_location'],
  },
  {
    id: 'step_target',
    title: '求职目标',
    description: '明确方向，便于后续项目描述对齐岗位',
    order: 2,
    questionIds: ['q_target_role', 'q_target_keywords', 'q_summary'],
  },
  {
    id: 'step_skills',
    title: '核心技能',
    description: '列出与目标岗位最相关的技能',
    order: 3,
    questionIds: ['q_skill_primary', 'q_skill_secondary', 'q_skill_years'],
  },
  {
    id: 'step_work_latest',
    title: '最近一份工作',
    description: '最近经历往往最受关注，尽量写清成果',
    order: 4,
    questionIds: [
      'q_work_org',
      'q_work_title',
      'q_work_start',
      'q_work_end',
      'q_work_responsibility',
      'q_work_achievement',
      'q_work_metric',
    ],
  },
  {
    id: 'step_project_main',
    title: '代表项目',
    description: '选 1 个最能体现能力的项目深入描述（STAR）',
    order: 5,
    questionIds: [
      'q_proj_name',
      'q_proj_role',
      'q_proj_period',
      'q_proj_background',
      'q_proj_action',
      'q_proj_result',
      'q_proj_tech',
    ],
  },
  {
    id: 'step_education',
    title: '教育背景',
    description: '学历与在校亮点（可选）',
    order: 6,
    questionIds: ['q_edu_skip', 'q_edu_school', 'q_edu_degree', 'q_edu_period', 'q_edu_highlight'],
  },
  {
    id: 'step_review',
    title: '确认生成',
    description: '预览并生成简历草稿',
    order: 7,
    questionIds: ['q_template', 'q_confirm'],
  },
]

/** 向导问题清单：按有效性排序，覆盖简历核心信息密度 */
export const RESUME_WIZARD_QUESTIONS: WizardQuestion[] = [
  // --- 基本信息 ---
  {
    id: 'q_name',
    stepId: 'step_basic',
    fieldPath: 'personal.name',
    type: 'text',
    label: '你的姓名或常用昵称？',
    placeholder: '张三',
    required: true,
    minLength: 1,
  },
  {
    id: 'q_headline',
    stepId: 'step_basic',
    fieldPath: 'personal.headline',
    type: 'text',
    label: '一句话介绍自己（职位 + 年限 + 专长）',
    placeholder: '5 年前端工程师，擅长 React 与工程化',
    required: true,
    minLength: 8,
    helpText: '对应 Profile.bio，会出现在简历顶部',
  },
  {
    id: 'q_email',
    stepId: 'step_basic',
    fieldPath: 'personal.email',
    type: 'text',
    label: '联系邮箱',
    placeholder: 'you@example.com',
    required: false,
  },
  {
    id: 'q_phone',
    stepId: 'step_basic',
    fieldPath: 'personal.phone',
    type: 'text',
    label: '手机号（可选）',
    required: false,
  },
  {
    id: 'q_location',
    stepId: 'step_basic',
    fieldPath: 'personal.location',
    type: 'text',
    label: '所在城市',
    placeholder: '上海',
    required: false,
  },

  // --- 求职目标 ---
  {
    id: 'q_target_role',
    stepId: 'step_target',
    fieldPath: 'meta.targetRole',
    type: 'text',
    label: '你正在申请什么岗位？',
    placeholder: '高级前端工程师',
    required: true,
  },
  {
    id: 'q_target_keywords',
    stepId: 'step_target',
    fieldPath: 'meta.targetKeywords',
    type: 'tags',
    label: 'JD 中的 3-5 个关键词（技术栈或能力）',
    placeholder: 'React, TypeScript, 性能优化',
    required: false,
    helpText: '用于后续突出相关项目与技能',
  },
  {
    id: 'q_summary',
    stepId: 'step_target',
    fieldPath: 'summary',
    type: 'textarea',
    label: '个人总结（2-4 句话：背景 + 优势 + 求职意向）',
    required: true,
    minLength: 30,
  },

  // --- 技能 ---
  {
    id: 'q_skill_primary',
    stepId: 'step_skills',
    fieldPath: 'skills.primary',
    type: 'tags',
    label: '最擅长的 3-5 项技能',
    placeholder: 'React, TypeScript, Node.js',
    required: true,
  },
  {
    id: 'q_skill_secondary',
    stepId: 'step_skills',
    fieldPath: 'skills.secondary',
    type: 'tags',
    label: '熟悉或了解的其他技能（可选）',
    required: false,
  },
  {
    id: 'q_skill_years',
    stepId: 'step_skills',
    fieldPath: 'skills.experienceYears',
    type: 'number',
    label: '相关领域总工作年限（年）',
    required: false,
  },

  // --- 最近工作 ---
  {
    id: 'q_work_org',
    stepId: 'step_work_latest',
    fieldPath: 'workExperiences[0].organization',
    type: 'text',
    label: '最近就职的公司/组织名称',
    required: true,
  },
  {
    id: 'q_work_title',
    stepId: 'step_work_latest',
    fieldPath: 'workExperiences[0].title',
    type: 'text',
    label: '职位名称',
    required: true,
  },
  {
    id: 'q_work_start',
    stepId: 'step_work_latest',
    fieldPath: 'workExperiences[0].startDate',
    type: 'month',
    label: '入职时间',
    required: true,
  },
  {
    id: 'q_work_end',
    stepId: 'step_work_latest',
    fieldPath: 'workExperiences[0].endDate',
    type: 'month',
    label: '离职时间（在职请留空或填「至今」）',
    required: false,
  },
  {
    id: 'q_work_responsibility',
    stepId: 'step_work_latest',
    fieldPath: 'workExperiences[0].bullets.responsibility',
    type: 'textarea',
    label: '主要职责是什么？（1-3 条，每条一行）',
    required: true,
    minLength: 20,
  },
  {
    id: 'q_work_achievement',
    stepId: 'step_work_latest',
    fieldPath: 'workExperiences[0].bullets.achievement',
    type: 'textarea',
    label: '最有代表性的成果？（尽量具体）',
    required: true,
    minLength: 20,
    helpText: '避免「负责开发」；改为「主导 XX 模块，上线后 DAU +20%」',
  },
  {
    id: 'q_work_metric',
    stepId: 'step_work_latest',
    fieldPath: 'workExperiences[0].bullets.metric',
    type: 'textarea',
    label: '可量化的数据（性能、用户量、效率提升等，可选）',
    required: false,
  },

  // --- 代表项目 STAR ---
  {
    id: 'q_proj_name',
    stepId: 'step_project_main',
    fieldPath: 'projects[0].title',
    type: 'text',
    label: '项目名称',
    required: true,
  },
  {
    id: 'q_proj_role',
    stepId: 'step_project_main',
    fieldPath: 'projects[0].role',
    type: 'text',
    label: '你在项目中的角色',
    placeholder: '前端负责人 / 独立开发者',
    required: true,
  },
  {
    id: 'q_proj_period',
    stepId: 'step_project_main',
    fieldPath: 'projects[0].period',
    type: 'text',
    label: '项目周期',
    placeholder: '2024-01 — 2024-06',
    required: true,
  },
  {
    id: 'q_proj_background',
    stepId: 'step_project_main',
    fieldPath: 'projects[0].highlights.situation',
    type: 'textarea',
    label: '【情境】项目背景与要解决什么问题？',
    required: true,
    minLength: 20,
  },
  {
    id: 'q_proj_action',
    stepId: 'step_project_main',
    fieldPath: 'projects[0].highlights.action',
    type: 'textarea',
    label: '【行动】你具体做了什么？',
    required: true,
    minLength: 30,
  },
  {
    id: 'q_proj_result',
    stepId: 'step_project_main',
    fieldPath: 'projects[0].highlights.result',
    type: 'textarea',
    label: '【结果】取得了什么可验证的结果？',
    required: true,
    minLength: 20,
  },
  {
    id: 'q_proj_tech',
    stepId: 'step_project_main',
    fieldPath: 'projects[0].technologies',
    type: 'tags',
    label: '使用的技术栈',
    required: true,
  },

  // --- 教育 ---
  {
    id: 'q_edu_skip',
    stepId: 'step_education',
    fieldPath: 'education.skip',
    type: 'select',
    label: '是否填写教育背景？',
    required: true,
    options: [
      { value: 'no', label: '填写' },
      { value: 'yes', label: '跳过' },
    ],
  },
  {
    id: 'q_edu_school',
    stepId: 'step_education',
    fieldPath: 'educations[0].school',
    type: 'text',
    label: '学校名称',
    required: false,
  },
  {
    id: 'q_edu_degree',
    stepId: 'step_education',
    fieldPath: 'educations[0].degree',
    type: 'text',
    label: '学历 / 专业',
    required: false,
  },
  {
    id: 'q_edu_period',
    stepId: 'step_education',
    fieldPath: 'educations[0].period',
    type: 'text',
    label: '就读时间',
    placeholder: '2017-09 — 2021-06',
    required: false,
  },
  {
    id: 'q_edu_highlight',
    stepId: 'step_education',
    fieldPath: 'educations[0].bullets',
    type: 'textarea',
    label: '在校亮点（奖项、方向，可选）',
    required: false,
  },

  // --- 确认 ---
  {
    id: 'q_template',
    stepId: 'step_review',
    fieldPath: 'meta.templateId',
    type: 'select',
    label: '选择简历模板',
    required: true,
    options: [
      { value: 'tpl_classic_zh', label: '经典中文' },
      { value: 'tpl_modern_zh', label: '现代紧凑' },
    ],
  },
  {
    id: 'q_confirm',
    stepId: 'step_review',
    fieldPath: '_confirm',
    type: 'select',
    label: '确认根据以上回答生成简历草稿？',
    required: true,
    options: [
      { value: 'yes', label: '生成' },
      { value: 'back', label: '返回修改' },
    ],
  },
]
